controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - lin_x
      - lin_y
      - lin_z
      - rot_x
      - rot_y
      - rot_z

